Repository ArduPilot/ardupilot_wiki, pull requests merged in 2021-04, with the labels that each got.

#3417 Add airspeed param setup page
  plane/source/docs/airspeed-parameters-setup.rst
  plane/source/docs/plane-configuration-landing-page.rst
Labels: plane-wiki

#2839 Update Lua bindings documentation
  common/source/docs/common-lua-scripts.rst
Labels: DelayMerge, common-wiki

#3329 Bi-directional dshot
  common/source/docs/common-blheli32-passthru.rst
  common/source/docs/common-dshot-blheli32-telemetry.rst
Labels: DelayMerge

#3173 common-osd-overview.rst: add callsign panel and fonts from SD
  common/source/docs/common-osd-overview.rst
Labels: DelayMerge

#3348 Remove resolved issue
  common/source/docs/common-uavcan-escs.rst
Labels: DelayMerge

#3450 Add filesystem descriptions in dev and link in MP
  dev/source/docs/filesystems.rst
  dev/source/docs/learning-the-ardupilot-codebase.rst
  dev/source/images/directory-tree.jpg
  planner/source/docs/mission-planner-configuration-and-tuning.rst
Labels: dev-wiki

#3477 4.1: Add new PID-FF manual tuning page for plane
  images/PID-controller.jpg
  images/ff1.png
  images/ff2.png
  plane/source/docs/new-roll-and-pitch-tuning.rst
Labels: WIP

#2948 Dev: AirSim: Add info about Rangefinder
  dev/source/docs/sitl-with-airsim.rst
Labels: DelayMerge
