Repository ArduPilot/ardupilot_wiki, pull requests merged in 2022-03, with the labels that each got.

#4176 4.2 Update Q_OPTIONS
  plane/source/docs/quadplane-parameters.rst
Labels: DelayMerge

#4175 4.2 Add warning about good GPS for compass learn
  common/source/docs/common-compass-setup-advanced.rst
Labels: DelayMerge

#4174 4.2: add note re VTOL level trim for roll
  plane/source/docs/guide-tailsitter.rst
Labels: DelayMerge

#4154 4.2 update to battery monitoring setup page
  common/source/docs/common-power-module-configuration-in-mission-planner.rst
Labels: DelayMerge

#4146 Update QuadPlane weathervaning params and actions
  plane/source/docs/quadplane-weathervaning.rst
Labels: DelayMerge

#4103 Add page on scripting parameters
  common/source/docs/common-lua-scripts.rst
  common/source/docs/common-scripting-parameters.rst
Labels: DelayMerge

#4098 Add transition failure actions
  plane/source/docs/quadplane-transitions.rst
Labels: DelayMerge

#4096 Add Aerobatics page
  common/source/docs/common-scripting-aerobatics.rst
  plane/source/docs/flight-features.rst
Labels: DelayMerge

#4129 tradheli- update internal RSC governor wiki
  copter/source/docs/traditional-helicopter-internal-rsc-governor.rst
  copter/source/docs/traditional-helicopter-rsc-setup.rst
  images/internal_governor.png
Labels: DelayMerge, tradheli-wiki

#4160 RC Failsafe update
  plane/source/docs/apms-failsafe-function.rst
Labels: DelayMerge

#4192 Tradheli: add videos for autotune feature
  copter/source/docs/traditional-helicopter-autotune.rst
  copter/source/docs/traditional-helicopter-tuning-preparing.rst
Labels: tradheli-wiki

#4242 Tradheli- add log analysis section to improve autotune wiki
  copter/source/docs/traditional-helicopter-autotune.rst
  copter/source/images/Tradheli_FF_log_example.png
  copter/source/images/Tradheli_angle_P_tuning_log_example.png
Labels: tradheli-wiki
