Repository ArduPilot/ardupilot_wiki, pull requests merged in 2023-04, with the labels that each got.

#4960 add wind comp Z coeff params
  common/source/docs/common-future-wiki-changes.rst
Labels: DelayMerge

#4961 Add copter specific weathervaning
  copter/source/docs/copter-flight-features.rst
  copter/source/docs/weathervaning.rst
Labels: DelayMerge

#4976 Add TKOFF_GND_PITCH param
  plane/source/docs/automatic-takeoff.rst
Labels: DelayMerge

#4977 4.4: add FS_GCS_TIMEOUT
  rover/source/docs/rover-failsafes.rst
Labels: DelayMerge

#4985 Add DO_JUMP_TAG cmds
  common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst
Labels: DelayMerge

#4992 Add Payload Place params for Copter
  copter/source/docs/mission-command-list.rst
Labels: DelayMerge

#5000 Add Copter Throttle Boost
  common/source/docs/common-tuning.rst
  copter/source/docs/throttle-boost.rst
Labels: DelayMerge

#5007 add new VTX_OPTIONS
  common/source/docs/common-vtx.rst
Labels: DelayMerge

#5017 add MPPT enable aux switch
  common/source/docs/common-packetdigital-mppt.rst
Labels: DelayMerge

#5018 Add BDShot versions of Pixhawk6C and ZealotH7
  common/source/docs/common-holybro-pixhawk6C.rst
  common/source/docs/common-qiotek-zealoth7.rst
Labels: DelayMerge

#5025 add BRD_SD_MISSION param
  common/source/docs/common-planning-a-mission-with-waypoints-and-events.rst
Labels: DelayMerge

#5026 Update winch baud rates
  common/source/docs/common-daiwa-winch.rst
Labels: DelayMerge

#5027 add SURFTRAK_TC parameter
  copter/source/docs/terrain-following-manual-modes.rst
Labels: DelayMerge

#5034 add FFT post filter info
  common/source/docs/common-imu-fft.rst
  common/source/docs/common-imu-notch-filtering.rst
Labels: DelayMerge

#5037 add new CAN drive options for 4.4
  common/source/docs/common-uavcan-setup-advanced.rst
Labels: DelayMerge

#5039 update camera parameters
  common/source/docs/common-camera-shutter-with-servo.rst
  common/source/docs/common-cameras-and-gimbals.rst
  common/source/docs/common-flir-vue-pro.rst
  common/source/docs/common-pixhawk-camera-trigger-setup.rst
  common/source/docs/common-pixhawk-overview.rst
  common/source/docs/common-siyi-zr10-gimbal.rst
  common/source/docs/common-viewpro-gimbal.rst
Labels: DelayMerge

#4999 add plane payload place mission item
  common/source/docs/common-auxiliary-functions.rst
  common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst
Labels: DelayMerge

#4965 Common: Add optical flow on rover
  common/source/docs/common-advanced-configuration.rst
  common/source/docs/common-archived-topics.rst
  common/source/docs/common-arkflow.rst
  common/source/docs/common-cheerson-cxof.rst
  common/source/docs/common-hereflow.rst
  common/source/docs/common-mouse-based-optical-flow-sensor-adns3080.rst
  common/source/docs/common-non-gps-navigation-landing-page.rst
  common/source/docs/common-openmv-optflow.rst
  common/source/docs/common-optical-flow-sensor-setup.rst
  common/source/docs/common-optical-flow-sensors-landingpage.rst
  common/source/docs/common-optional-hardware.rst
  common/source/docs/common-px4flow-overview.rst
  common/source/docs/common-upixels-upflow.rst
Labels: DelayMerge

#4954 tradheli-update for angle P autotune test
  copter/source/docs/traditional-helicopter-autotune.rst
Labels: DelayMerge, tradheli-wiki

#4966 Tradheli: explanation of manual autorotation setup
  copter/source/docs/traditional-helicopter-autorotation.rst
  copter/source/docs/traditional-helicopter-rsc-setup.rst
  copter/source/docs/traditional-helicopters.rst
Labels: DelayMerge, tradheli-wiki

#5068 Common: Add RockBLOCK instructions
  common/source/docs/common-telemetry-landingpage.rst
  common/source/docs/common-telemetry-rockblock.rst
  images/RockBLOCK-9603-Angled.jpg
Labels: DelayMerge

#4964 Rover: add new GCS failsafe timeout param and improve failsafe descri…
  rover/source/docs/rover-failsafes.rst
Labels: rover-wiki

#5089 Common: viewpro driver links for 4.4 and 4.5
  common/source/docs/common-viewpro-gimbal.rst
Labels: bug, common-wiki
