Repository ArduPilot/ardupilot_wiki, pull requests merged in 2024-05, with the labels that each got.

#5960 Add research paper reference for UAS automation/handling qualities
  dev/source/docs/acadamic-works.rst
Labels: dev-wiki

#5938 4.6:add NanoRadar MR72
  common/source/docs/common-rangefinder-landingpage.rst
  common/source/docs/common-rangefinder-mr72.rst
  images/MR72.png
Labels: 4.6Wiki

#5890 build deps for ros2 and gz
  dev/source/docs/ros2.rst
Labels: MergeOnCIPass

#6013 Patch 1 : Completed the TODO on MAV_CMD_DO_JUMP_TAG with screenshots.
  common/source/docs/common-mavlink-mission-command-messages-mav_cmd.rst
  images/MissionList_DoJump_Tag.png
Labels: MergeOnCIPass
